# Generated by Django 5.1.1 on 2024-10-06 02:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_project_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion_del_curso', models.CharField(max_length=255)),
                ('descripcion_curso', models.TextField()),
                ('fecha_curso', models.DateField()),
                ('numero_horas', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='static/blog/images')),
                ('fecha', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
